### ISSUE TITLE
Getting the same number of pings from different histograms

### ISSUE THREAD

**Issue by vladikoff** [mozilla/emr-bootstrap-spark#12]
![](http://v14d.com/i/567cad3de30ed.jpg)

@vitillo @mreid-moz hey do you know why the above telemetry query returns the same number?

Code:

```

In [22]:

sc.defaultParallelism
Out[22]:
16
In [23]:

pings = get_pings(sc, app="Firefox", channel="nightly", submission_date=("20151207", "20151214"), fraction=0.1)
In [24]:

fxa_hawk = get_pings_properties(pings, "payload/histograms/FXA_HAWK_ERRORS", with_processes=True)
print fxa_hawk.count();
105425
In [25]:

fxa_conf = get_pings_properties(pings, "payload/histograms/FXA_CONFIGURED", with_processes=True)
print fxa_conf.count();
105425
```

**Comment by vladikoff** [comment]
I guess I need to process the pings above.

fxa_conf is a ` "kind": "flag",`
fxa_hawk is a ` "kind": "count",`

How can I get % of true / false ( i assume that is what `flag` is`) from get pings?

How can I get average count of FXA_HAWK_ERRORS?

For this second one I know `get_one_ping_per_client` exists but I guess it would be useful to have something like `get_most_recent_ping_per_client`? This way I can get the count of errors for the client in the end of my `submission_date` range (i.e end of week). 

One thing I'm confused about re: [FXA_HAWK_ERRORS](http://mxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/Histograms.json#9625) and [desktop code](http://mxr.mozilla.org/mozilla-central/source/services/fxaccounts/FxAccountsClient.jsm#427), would this give me a number of times HAWK ERROR occurred during the `submission_date` range or is it total number of times the HAWK ERROR occurred in the firefox profile?

Sorry I don't know all the details about FF Desktop Telemetry. Any help with this is appreciated! cc @georgf

**Comment by mreid-moz** [comment]
The `get_pings_properties` function doesn't do any filtering - what you get out is one record per submission.  As you discovered, you have to do further filtering to see if the histogram was present (and what it recorded).

> How can I get % of true / false ( i assume that is what flag is`) from get pings?

Roberto, please correct me if I'm wrong, but to determine true vs. false for a flag histogram, you can do something like:
```python
c = fxa_conf.first()["payload/histograms/FXA_CONFIGURED"]
fxa_configured = None ## unknown (not set in this submission either way)
if c[1] > 0:
        fxa_configured = True
elif c[0] > 0:
        fxa_configured = False
```

> How can I get average count of FXA_HAWK_ERRORS?

If you want an average count per-client, you should add the `clientId` field to your `get_pings_properties` call, then you can group by clientId and count the occurrences per client over the period you're interested in.  Note that the pings are single points in time, so you can't just look at the most recent ping to get a count over the entire period.

> One thing I'm confused about re: FXA_HAWK_ERRORS and desktop code, would this give me a number of times HAWK ERROR occurred during the submission_date range or is it total number of times the HAWK ERROR occurred in the firefox profile?

The count is the number of times during a single browser session (since startup). There can be many pings for the same `submission_date` for a given clientId. There is some nuance here, there are two types of pings you can look at - by default you get `saved-session` pings which cover the full period from startup to shutdown. You can also look at `main` pings (by setting `doc_type='main'` in `get_pings`) which break browser usage down even further into subsessions, each covering a period of not more than one day.

**Comment by vladikoff** [comment]
@mreid-moz Thanks for the detailed response, I shall try out the filtering this week!

**Comment by vitillo** [comment]
@mreid-moz 
Note that flag histograms are already [represented](https://github.com/mozilla/python_moztelemetry/blob/master/moztelemetry/histogram.py#L148) as booleans with `get_pings_properties`.

**Comment by mreid-moz** [comment]
Ah, good to know. I was thinking of `"kind": "boolean"`

**Comment by vladikoff** [comment]
@vitillo @mreid-moz, could you tell me if there is anything wrong with this calculation:
(or if there are any nits I should be aware of)

```
# Get the pings
pings = get_pings(sc, app="Firefox", channel="nightly", submission_date=("20151207", "20151215"), fraction=0.1)

# Get only client id and FXA_CONFIGURED
subset = get_pings_properties(pings, ["clientId", "payload/histograms/FXA_CONFIGURED"])

# Get only unique per client (not sure which one it picks for some client X)
# There could be 10 pings from the same client, and we might get a FALSE even though the client connected later on or was connected before.
subset = get_one_ping_per_client(subset)

# TOTAL is all clients that reported "FXA_CONFIGURED" - true or false
print "Total is: " + str(subset.count())

# confd ONLY clients that have FXA_CONFIGURED in the date range of "20151207", "20151215"

confd = subset.filter(lambda x: x['payload/histograms/FXA_CONFIGURED'] == True)
confd_count = confd.count()
print "FxA Configured: " + str(confd_count)
print "FxA Not Configured:" + str(subset.count() - confd_count)
```

Using this data I can answer the question: 

"What is the percentage of Firefox (Nightly) profiles that have Firefox Accounts connected between 20151207 and  20151215?" 

Is the above correct?

**Comment by vladikoff** [comment]
@vitillo @mreid-moz Two other things I noticed:

1. If I do not pass `channel="release",` in `get_pings` then the query hangs for a long time, never completes, even if I set fraction to 0.10

2. When I set ` channel="release",` How come the value becomes `'payload/histograms/FXA_CONFIGURED': None,`, with `nightly` and `beta` I get True / False values

**Comment by vitillo** [comment]
@vladikoff 

Your analysis isn't correct. 

Specifying `fraction=0.1` in `get_pings` returns 10% of all the pings sampled randomly. This means that for a certain client you might not get all of its corresponding sessions in that time frame, which is ultimately what you need for your analysis. Instead of specifying a fraction in `get_pings` use a filter to sample by `clientId`;  `sampleId` corresponds to `crc32(clientId) % 100`, so you shoud use that to consider only the submissions belonging to N% of the users.

You should also to iterate over the sessions of a profile and compute the logical OR of all the FXA_CONFIGURED values, which tells you if that profile was signed in FXA in at least one of its sessions.

Note that `get_pings_properties` returns `None` for an attribute if that attribute is not present in a submission.

**Comment by mreid-moz** [comment]
> `# Get only unique per client (not sure which one it picks for some client X)`

The single ping per client is selected randomly.

> If I do not pass channel="release", in get_pings then the query hangs for a long time, never completes, even if I set fraction to 0.01

Do you mean if you *do* pass `channel="release"`? This is expected - the release channel contains a huge volume of data - many many terabytes. Even a small fraction can be very large.  We are working on some approaches to make this kind of analysis more tractable / performant.

> Note that get_pings_properties returns None for an attribute if that attribute is not present in a submission.

This is somewhat concerning - the `FXA_CONFIGURED` histogram should be collected on all channels (it has the `"releaseChannelCollection": "opt-out"` flag set in `Histograms.json`. @vladikoff Are you seeing a large fraction of pings on the release channel with `None` for this histogram?

**Comment by vladikoff** [comment]
Hm I wrote a response comment, but it disappeared. anyway:

> @vladikoff Are you seeing a large fraction of pings on the release channel with None for this histogram?

Yeah it was not able to find any `True` or `False` values from the 0.01% sample. I noticed that telemetry.mozilla.org is not showing values for FF42, but does show values for FF43. 
Can I query for Firefox 43+ in my query? (So I don't have to update the version all the time in my books)

**Comment by mreid-moz** [comment]
Yep:

`get_pings(sc, app="Firefox", channel="nightly", submission_date=("20151207", "20151214"), version=("43.0","49.0"), fraction=0.1)`

in this case, `49.0` is the "max" value, inclusive (same as submission_date).

**Comment by vladikoff** [comment]
> Yep:
get_pings(sc, app="Firefox", channel="nightly", submission_date=("20151207", "20151214"), version=("43.0","49.0"), fraction=0.1)
in this case, 49.0 is the "max" value, inclusive (same as submission_date).

Awesome, thank you so much.


>Instead of specifying a fraction in get_pings use a filter to sample by clientId; sampleId corresponds to crc32(clientId) % 100, so you shoud use that to consider only the submissions belonging to N% of the users.

@vitillo do you have an example of this anywhere?

**Comment by vitillo** [comment]
@vladikoff You could use something like `rdd.filter(lambda x: x["sampleId"] == 0)` to retrieve all submissions of profiles for which `crc32(clientId) % 100 == 0`.

**Comment by vladikoff** [comment]
> @vladikoff You could use something like rdd.filter(lambda x: x["sampleId"] == 0) to retrieve all submissions of profiles for which crc32(clientId) % 100 == 0.

Thanks for clarifying and I **really** appreciate yours and Mark's help with this.

**Comment by vladikoff** [comment]
I came to a conclusion that we won't be able to create a percentage based graph using the FXA_CONFIGURED probe. We only get one value "FXA_CONFIGURED=True" and are not able to compare it with anything else.

We can build a graph to answer "How *many* profiles set a signed in user in a week?" However we are not interested in that raw number.

cc @rfk

**Comment by mreid-moz** [comment]
You can get the total number of clientIds that submitted any ping and establish a percentage based on that.
